services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/home/rexes/backend
    ports:
      - "8000:8000"
    env_file:
      - .env
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/home/node/frontend
      - /home/node/frontend/node_modules
    ports:
      - "5173:5173"
